config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/gdkrmr/dimRed:
      branch: master
      repo: https://github.com/gdkrmr/dimRed
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/gdkrmr/dimRed git:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-saffron-stingray.sh
        container: qc.acc_scanty-corn-wallaby
  QC.Doc:
    repos:
      github.com/gdkrmr/dimRed find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-russet-whale.sh
        container: qc.doc_lumpy-lemon-chow
      github.com/gdkrmr/dimRed git:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-heliotrope-kakapo.sh
        container: qc.doc_snippy-cream-vole
  QC.Lic:
    repos:
      github.com/gdkrmr/dimRed licensee:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-azure-eel.sh
        container: qc.lic_woozy-seashell-crocodile
  QC.Ver:
    repos:
      github.com/gdkrmr/dimRed get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-chocolate-woodlouse.sh
        container: qc.ver_scanty-saffron-frise
timeout: 5400
